#pragma once

#define IDI_ICON_T3DX					101

#define IDC_CURSOR_BLUE					201
#define IDC_CURSOR_GREEN				202

#define IDR_SOUND_BEAM					301
#define IDR_SOUND_CREATE				302
#define IDR_SOUND_TECHNO				303
#define IDR_SOUND_TELEPORT				304
#define IDR_SOUND_WARP					305


#define IDR_MENU_MAINMENU				1000

#define IDR_MENU_FILE_ID_EXIT			1001

#define IDR_MENU_PLAY_ID_BEAM			2001
#define IDR_MENU_PLAY_ID_CREATE			2002
#define IDR_MENU_PLAY_ID_TECHNO			2003
#define IDR_MENU_PLAY_ID_TELEPORT		2004
#define IDR_MENU_PLAY_ID_WARP			2005

#define IDR_MENU_HELP_ID_ABOUT			3001
