#pragma once

#define IDI_ICON_T3DX			101

#define IDC_CURSOR_BLUE			201
#define IDC_CURSOR_GREEN		202

#define IDR_SOUND_BEAM			301
#define IDR_SOUND_CREATE		302
#define IDR_SOUND_TECHNO		303
#define IDR_SOUND_TELEPORT		304
#define IDR_SOUND_WARP			305
